---
#
# https://www.home-assistant.io/docs/installation/
#
homeassistant:
  # https://www.home-assistant.io/docs/authentication/providers/
  auth_providers:
    - type: homeassistant
  # https://www.home-assistant.io/docs/authentication/multi-factor-auth/
  auth_mfa_modules:
    - name: Two-Factor Authentication
      type: totp
