---
# Let's party!

blueprint:
  source_url: https://github.com/niro1987/homeassistant-config/blob/main/blueprints/automation/niro1987/party_lights.yaml

  name: Party Lights!

  description: >-
    Party Lights!

  domain: automation

  input:
    light:
      name: Light
      description: Select your party lights! Create a group to control many lights.
      selector:
        entity:
          domain: light
    switch:
      name: Party Mode
      description: The helper switch to turn the party mode on and off.
      selector:
        entity:
          domain: input_boolean
    speed:
      name: Speed
      description: The time in milliseconds between light changes.
      selector:
        number:
          min: 100
          max: 5000
          mode: box
          unit_of_measurement: milliseconds

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input switch

action:
  - service: scene.create
    data:
      scene_id: party_lights_pre_state
      snapshot_entities:
        - !input light
  - repeat:
      while:
        - condition: state
          entity_id: !input switch
          state: "on"
      sequence:
        - service: light.turn_on
          target:
            entity_id: !input light
          data:
            rgb_color:
              [
                "{{ (range(0, 255)|random) }}",
                "{{ (range(0, 255)|random) }}",
                "{{ (range(0, 255)|random) }}",
              ]
            brightness: "{{ (range(50, 250)|random) }}"
            transition: 0.1
        - delay:
            milliseconds: !input speed
  - delay:
      milliseconds: !input speed
  - service: scene.turn_on
    target:
      entity_id: scene.party_lights_pre_state
