---
substitutions:
  devicename: slaapkamer_lily
  static_ip: !secret slaapkamer_lily_ip

packages:
  device: !include common/devices/sonoff_mini.yaml
  base: !include common/default_base.yaml

output:
  - platform: gpio
    id: output_1
    pin: GPIO12

binary_sensor:
  - platform: gpio
    id: binary_1
    name: 'Slaapkamer Lily Switch'
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true

light:
  - platform: binary
    id: light_1
    name: 'Slaapkamer Lily Relay'
    output: output_1
